<a href="https://colab.research.google.com/github/danielli-arcari/treinamento2_machinelearning/blob/main/SegundoTreino_LendoDadosInternet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [98]:
import pandas as pd

uri = "https://gist.githubusercontent.com/guilhermesilveira/b9dd8e4b62b9e22ebcb9c8e89c271de4/raw/c69ec4b708fba03c445397b6a361db4345c83d7a/tracking.csv"
dados = pd.read_csv(uri)
dados.head()

   inicial  palestras  contato  comprou  patrocinio
0        1          1        0        0           0
1        1          1        0        0           0
2        1          1        0        0           0
3        1          1        0        0           0
4        1          1        0        0           0

In [99]:
y = dados["comprou"]
y.head()

0    0
1    0
2    0
3    0
4    0
Name: comprou, dtype: int64

In [100]:
x = dados[["inicial", "palestras",	"contato",	"patrocinio"]]
x.head()

   inicial  palestras  contato  patrocinio
0        1          1        0           0
1        1          1        0           0
2        1          1        0           0
3        1          1        0           0
4        1          1        0           0

In [101]:
dados.shape

(99, 5)

In [102]:
from sklearn.svm import LinearSVC

modelo = LinearSVC()
modelo.fit(treino_x, treino_y)

LinearSVC()

In [103]:
treino_x = x[:75]
treino_y = y[:75]

teste_x = x[75:]
teste_y = y[75:]

print(f"Treinaremos com {len(treino_x)} elementos")
print(f"Testaremos com {len(teste_x)} elementos")

Treinaremos com 75 elementos
Testaremos com 24 elementos

In [104]:
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

modelo = LinearSVC()
modelo.fit(treino_x, treino_y)
previsoes = modelo.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes) * 100
print(f"A acurácia foi de {acuracia:.2f}%")

A acurácia foi de 95.83%

In [105]:
from sklearn.model_selection import train_test_split

train_test_split(x, y)

[    inicial  palestras  contato  patrocinio
 62        0          0        1           0
 72        0          0        1           1
 71        0          0        1           0
 50        1          1        0           0
 3         1          1        0           0
 ..      ...        ...      ...         ...
 37        0          0        1           0
 76        0          0        1           0
 24        1          0        1           0
 87        0          0        1           0
 22        0          0        1           0

 [74 rows x 4 columns],
     inicial  palestras  contato  patrocinio
 46        1          0        1           0
 36        1          0        1           0
 65        0          1        1           0
 75        0          1        0           0
 29        0          0        1           1
 25        1          1        1           0
 34        1          0        1           0
 43        1          0        1           0
 86        1          1        0           0
 70        1          1        0           0
 92        1          1        0           0
 20        0          0        1           0
 59        0          0        1           0
 81        0          0        1           0
 80        0          0        1           0
 96        0          0        1           0
 97        0          1        0           0
 4         1          1        0           0
 73        0          0        1           0
 27        1          0        1           0
 57        1          1        0           0
 63        0          1        0           0
 66        0          0        1           0
 44        0          0        1           0
 55        1          1        0           0,
 62    0
 72    0
 71    0
 50    0
 3     0
      ..
 37    0
 76    0
 24    1
 87    0
 22    0
 Name: comprou, Length: 74, dtype: int64,
 46    1
 36    1
 65    1
 75    0
 29    0
 25    1
 34    1
 43    1
 86    0
 70    0
 92    0
 20    0
 59    0
 81    0
 80    0
 96    0
 97    0
 4     0
 73    0
 27    1
 57    0
 63    0
 66    0
 44    0
 55    0
 Name: comprou, dtype: int64]

In [106]:
from sklearn.model_selection import train_test_split

treino_x, teste_x, treino_y, teste_y = train_test_split(x, y)

print(f"Treinaremos com {len(treino_x)} elementos")
print(f"Testaremos com {len(teste_x)} elementos")

Treinaremos com 74 elementos
Testaremos com 25 elementos

In [107]:
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

SEED = 20

treino_x, teste_x, treino_y, teste_y = train_test_split(x, y, random_state = SEED, stratify=y)

print(f"Treinaremos com {len(treino_x)} elementos")
print(f"Testaremos com {len(teste_x)} elementos")

modelo = LinearSVC()
modelo.fit(treino_x, treino_y)
previsoes = modelo.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes) * 100
print(f"A acurácia foi de {acuracia:.2f}%")

Treinaremos com 74 elementos
Testaremos com 25 elementos
A acurácia foi de 96.00%

In [108]:
treino_y.value_counts()

comprou
0    49
1    25
Name: count, dtype: int64

In [109]:
teste_y.value_counts()

comprou
0    17
1     8
Name: count, dtype: int64